// Auto-generated types from Puzzlet
// Do not edit this file directly

interface CustomersupportIn {
  emailContent: string;
}


type CustomersupportOut = string

interface Customersupport {
  input: CustomersupportIn;
  output: CustomersupportOut;
}

export default interface PuzzletTypes {
  "customer_support.prompt.mdx": Customersupport
}
